STORAGE_DIR=$(readlink -f ./.tmp)

# pcmd
PROMPTCTL="../../target/debug/promptctl"
HOME_DIR=$STORAGE_DIR/home
CONFIG_DIR=$STORAGE_DIR/config
CONFIG_PATH=$CONFIG_DIR/config.toml
INSTALL_DIR=$HOME_DIR/installed
PROMPTS_DIR=$CONFIG_DIR/prompts

export PROMPTCMD_HOME_DIR=$HOME_DIR
export PROMPTCMD_CONFIG_DIR=$CONFIG_DIR
export PROMPTCMD_PROMPTS_DIR=$PROMPTS_DIR
export PROMPTCMD_INSTALL_DIR=$INSTALL_DIR
## ssh
SSH_DIR=$STORAGE_DIR/ssh
SSH_IDENTITY=$SSH_DIR/id_ed25519
SSH_PASSWORD=000000

